### ISSUE TITLE
Help wanted for the project?

### ISSUE THREAD

**Issue by 0xYao** [harrylimp/EBC#24]
Heyo! Is this project welcomed for any contributions at all?

xD

**Comment by sli473** [comment]
Hey xD
This project has actually been inactive for two years, I don't think there'll really be a market for transferring business cards digitally while other business social platforms like LinkedIn exist, but feel free to make any pull requests you'd like for fun etc :D

**Comment by 0xYao** [comment]
> Hey xD
> This project has actually been inactive for two years, I don't think there'll really be a market for transferring business cards digitally while other business social platforms like LinkedIn exist, but feel free to make any pull requests you'd like for fun etc :D

Sounds good!
